### PR TITLE
Wrap JSX roots in hoisted sibling functions

### PR DESCRIPTION
**Pull request by jridgewell**

### CODE REVIEW

**Comment by thejameskyle** [comment]
Looks fine, but you may want to find ways to eliminate some of this state being added to nodes.

**Comment by jridgewell** [comment]
I could probably move `_iDOMisRoot` into the path's data object?

**Comment by thejameskyle** [comment]
Well, generally in babel the answer is nested visitors.

So the initial visitor hits a root iDOM node. It holds onto that information in memory and then creates a new visitor that traverses down the tree.

**Comment by jridgewell** [comment]
Pushing the nested visitor discussion into #29.

**Pull request merged**
