### PR TITLE
Early throw when using JSX Namespaces

### PR DESCRIPTION
**Pull request by jridgewell**

### CODE REVIEW

**Comment by thejameskyle** [comment]
What about?
https://github.com/babel-plugins/babel-plugin-incremental-dom/blob/master/test/fixtures/namespace/actual.js

**Comment by jridgewell** [comment]
That's a JSX Member Expression, but they call it a "namespace"d element.

**Comment by thejameskyle** [comment]
Can you rename the test then?

**Comment by jridgewell** [comment]
Updated.

**Comment by thejameskyle** [comment]
nice

**Comment by thejameskyle** [comment]
Want to release?

**Comment by jridgewell** [comment]
v2?

**Comment by thejameskyle** [comment]
namespaces were never supported, this will just start throwing an error yes?

**Comment by jridgewell** [comment]
> namespaces were never supported, this will just start throwing an error yes?

Yup.

But, we've also merged the Child AssignmentExpressions PR, which adds a lot of functionality.

**Comment by thejameskyle** [comment]
oh, yup 2.0

**Pull request merged**
