### PR TITLE
Hoist Static Attrs

### PR DESCRIPTION
**Pull request by jridgewell**
Following the [best practices](http://google.github.io/incremental-dom/#rendering-dom/statics-array) of iDOM, we should hoist our statics array as high as we can.

- For purely constant Static attributes (no key, or a literal key), we hoist the statics array to the Program node.
- When a variable key is defined, we hoist the Statics and replace the key's value with `undefined` in the array.
  - Once the "JSX" iDOM calls are run, we will assign the value of the key to the proper index of the array
- When we wrap a JSX element, we hoist the Statics to the scope of the eager attributes.

Implemented as an option for now, until I'm confident we've found the edge cases.

### CODE REVIEW

**Comment by thejameskyle** [comment]
Should cases like:

```js
function test(props) {
  props.key = 1;
  _statics31[3] = props.key;
  return elementVoid("div", props.key, _statics31);
}
```

Be resetting the value afterwards to avoid memory leaks?

```js
function test(props) {
  props.key = 1;
  _statics31[3] = props.key;
  var _result = elementVoid("div", props.key, _statics31);
  _statics31[3] = null;
  return _result;
}
```

**Comment by jridgewell** [comment]
We could, but these should be simple strings (or numbers, but really just strings).

**Comment by thejameskyle** [comment]
What about event handlers?

**Comment by jridgewell** [comment]
The `_statics31[3] = key` is only for the key attribute, objects (and functions) won't work properly with the `keyMap` inside iDOM.

**Comment by thejameskyle** [comment]
Ooh I see.

**Comment by jridgewell** [comment]
Good to go?

**Comment by thejameskyle** [comment]
Yeah, looks good.

**Pull request merged**
