### PR TITLE
Error on duplicate attributes

### PR DESCRIPTION
**Pull request by jridgewell**
This isn't directly enforced by JSX, but will cause in error in ES5 browsers. Thoughts on including it?

### CODE REVIEW

**Comment by thejameskyle** [comment]
Why would it error in ES5 environments if it gets turned into an array?

**Comment by jridgewell** [comment]
Re: https://github.com/babel/babel/issues/2462.

It won't cause an issue with iDOM, until we release the static-hoisting feature. Then it'll cause mayhem with duplicate `key` attributes.

**Comment by thejameskyle** [comment]
I don't see how static hoisting would introduce an issue?

**Comment by jridgewell** [comment]
See https://github.com/babel-plugins/babel-plugin-incremental-dom/blob/hoisting/src/helpers/extract-open-arguments.js#L44-L47. If we're hoisting, and the key attribute isn't a literal (and we're not eagerly evaluating attributes), we'll push `undefined` instead of the `key` variable reference:

```js
statics = ['id', 'id', 'key', 'key'];
// vs
statics = ['id', 'id', 'key', undefined];
```

If there are multiple key attributes, we'll have several `undefined`s in the array, and only the final `key` will be properly set.

**Pull request closed without merging**
