### PR TITLE
Throw compile-time error for unused JSX Elements

### LINKED ISSUE #13: JSX inside IncrementalDOM.patch(el, callback) is removed
```jsx
IncrementalDOM.patch(document.body, function () {
  <h1>suchwow</h1>
});
```

Works in `v1.0.3`

```jsx
_incrementalDom2['default'].patch(document.body, function () {
  elementOpen('h1');
    text('suchwow');
  elementClose('h1');
});
```
but in `v2.0.0` the JSX is simply removed, for noop

```jsx
_incrementalDom2['default'].patch(document.body, function () {});
```

A quick glance makes me guess it was the aptly named: https://github.com/babel-plugins/babel-plugin-incremental-dom/commit/9b5faf28ade0bf22570f6cd969d1b44fcad7ad97 "Preemptively remove useless JSX"

### PR DESCRIPTION
**Pull request by jridgewell**
Fixes #13.

### CODE REVIEW

**Comment by thejameskyle** [comment]
Cool, but you might want to follow the existing pattern in Babel for testing errors:

https://github.com/babel/babel/blob/91fb64eaf53c67a7ed7605aab71f8dcaa4d39ae2/packages/babel/test/fixtures/transformation/errors/syntax/options.json

This will eventually just be built into `babel-plugin test`

**Comment by thejameskyle** [comment]
Nice

**Comment by thejameskyle** [comment]
This looks good to merge whenever you feel like it

**Comment by thejameskyle** [comment]
Wanna release?

**Comment by jridgewell** [comment]
Still need you to review https://github.com/babel-plugins/babel-plugin-incremental-dom/pull/15.

**Pull request merged**
